environment:
  ELM_VERSION: "0.19.1"
  matrix:
  - nodejs_version: "12"
  - nodejs_version: "10"
  - nodejs_version: "8"

platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
